import json

NEW_ENTRIES = [

{"chunk_id": "pam_035", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How many people were in a WWII submarine crew?",
 "questions": ["How many men were on a submarine?", "How large was the crew of a WWII fleet submarine?", "How many sailors served on a submarine?"],
 "text": "How many people were in a WWII submarine crew?\n\nA US fleet submarine like the Pampanito carried about 80 men \u2014 roughly 10 officers and 70 enlisted sailors. The Balao class, to which Pampanito belongs, had a maximum complement of 85, though wartime patrols often ran slightly under that.\n\nIn a vessel 311 feet long and less than 28 feet at its widest, those 80 men lived, slept, worked, ate, and stood watch in conditions of extraordinary crowding. There were never enough bunks for everyone at the same time, which is why the \u201chot bunk\u201d system was used \u2014 a sailor coming off watch would climb into the bunk just vacated by someone going on watch, the mattress still warm.\n\nDespite the cramped conditions, a submarine crew functioned as a highly trained team. Every man had to qualify in every major system aboard \u2014 not just his own job. In an emergency, you might need any sailor to operate any piece of equipment. The Navy\u2019s word for this was \u201cqualified in submarines,\u201d and earning it was a point of pride."},

{"chunk_id": "pam_036", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What did the crew do for fun on a long patrol?",
 "questions": ["How did submariners entertain themselves?", "What recreation did submarine crews have?", "What was there to do on a submarine patrol?"],
 "text": "What did the crew do for fun on a long patrol?\n\nThe crew\u2019s mess \u2014 the small dining area in the middle of the boat \u2014 doubled as the only real recreation space on a fleet submarine. When men weren\u2019t eating, sleeping, or standing watch, this is where they gathered.\n\nCard games were the most popular pastime: poker, cribbage, acey-deucey (a Navy version of backgammon), and checkers. Many boats had a small record player or phonograph for music. Reading paperback books was common \u2014 crewmen shared novels and magazines until they fell apart. In the later years of the war, some submarines were equipped with a 16mm movie projector, and a rotation of films would be screened in the crew\u2019s mess.\n\nPatrol days were long and mostly routine. Ninety percent of a patrol was spent transiting to and from the patrol area, or waiting submerged during daytime hours. Men on the day watch might have several hours of free time. The boredom was interrupted by drills, maintenance, and \u2014 when it came \u2014 the sudden controlled chaos of a potential contact or attack. Veterans often recall that the monotony was harder to endure than the danger."},

{"chunk_id": "pam_037", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What was the toilet like on a submarine?",
 "questions": ["How did submariners use the bathroom?", "How did sailors go to the bathroom on a submarine?", "What was a submarine head like?", "How did you flush a toilet on a submarine?"],
 "text": "What was the toilet like on a submarine?\n\nOn a submarine, the toilet is called the \u201chead\u201d \u2014 standard Navy terminology. A fleet submarine had two heads: one for the officers and one for the crew. For 80 men, that was very limited.\n\nUsing the head on a submerged submarine was not simple. Because the boat was under pressure, the waste had to be blown outboard against sea pressure using compressed air \u2014 you couldn\u2019t just flush. The procedure involved a specific sequence of valves and levers, and signs were posted in each head explaining the steps. Getting the sequence wrong could result in sewage being blown back into the boat, covering the unfortunate user. Most veteran submariners have a story about this happening to someone.\n\nAt diving depths, the procedure became more complicated because higher pressure was required. Some submarines had sanitary tanks that held waste until the boat surfaced, when it could be discharged normally. The combination of the small number of heads, the complicated procedure, and the need to queue during busy periods made the head situation one of the reliable inconveniences of submarine life."},

{"chunk_id": "pam_038", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How did a submarine surface from underwater?",
 "questions": ["How did submarines come up from underwater?", "What is blowing ballast tanks?", "How do you surface a submarine?"],
 "text": "How did a submarine surface from underwater?\n\nTo surface, a submarine \u201cblew\u201d its ballast tanks \u2014 forcing out the seawater that made the boat heavy enough to submerge in the first place. High-pressure air stored in large banks of cylinders on the submarine was routed into the main ballast tanks, pushing the water out through flood holes in the bottom. As the tanks filled with air, buoyancy increased and the boat rose toward the surface.\n\nOnce the submarine broached \u2014 broke the surface \u2014 the bridge watch would open the conning tower hatch as soon as it was safe, and the lookouts and officer of the deck would climb topside to begin watching for aircraft and other threats. Surfacing was a vulnerable moment because the boat wasn\u2019t yet moving fast enough to dive quickly if a threat appeared.\n\nThe diesel engines would be started as soon as the induction mast was clear of the water, beginning the process of charging the batteries for the next submerged period. On the surface, the diesels ran constantly \u2014 the submarine used one or two engines to drive the boat and the others to charge batteries."},

{"chunk_id": "pam_039", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What was the procedure for an emergency dive?",
 "questions": ["What is a crash dive?", "How fast could a submarine dive?", "How did submarines dive quickly when attacked?", "What happened during a crash dive?"],
 "text": "What was the procedure for an emergency dive?\n\nAn emergency dive \u2014 called a \u201ccrash dive\u201d \u2014 was practiced constantly until the entire crew could execute it in their sleep. Typically triggered by a sighting of an enemy aircraft or surface ship, the goal was to get below the surface as fast as possible.\n\nThe diving alarm \u2014 two blasts of the klaxon, the distinctive \u201cah-OOH-ga\u201d sound \u2014 was the signal. Every man on the bridge scrambled below in a fixed order: lookouts first, then the officer of the deck, then the captain last, pulling the hatch shut behind him. The main ballast tank vents were opened and water flooded in. Full negative tanks were flooded for additional weight. The diving planes were angled steeply. The diesel engines were secured and the electric motors engaged.\n\nA well-drilled fleet submarine crew could go from surfaced to periscope depth \u2014 roughly 63 feet \u2014 in 30 to 60 seconds. Getting those extra few seconds could be the difference between escaping and being bombed. Submariners drilled on the crash dive over and over again until every motion was automatic."},

{"chunk_id": "pam_040", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What is a periscope and how was it used?",
 "questions": ["How did a periscope work?", "What did a submarine use a periscope for?", "How did the captain see through the periscope?"],
 "text": "What is a periscope and how was it used?\n\nA periscope is an optical instrument \u2014 essentially a long tube with prisms and lenses \u2014 that allows a submarine to observe the surface while remaining underwater. On a fleet submarine, the periscope extended from the conning tower and could be raised up through the hull to just above the waterline, allowing the captain to see the horizon without exposing the boat.\n\nFleet submarines typically carried two periscopes: a thicker \u201csearch\u201d periscope with higher magnification for long-range observation and low-light use, and a thinner \u201cattack\u201d periscope used during torpedo approaches. The attack scope presented a smaller surface signature \u2014 less wake, harder for a sharp-eyed lookout to spot.\n\nThe captain \u201cshot\u201d periscope bearings by raising the scope for only a few seconds at a time, taking a bearing and range estimate on the target, then immediately lowering it. Extended exposure risked detection. The data was fed into the Torpedo Data Computer in the conning tower, which calculated the torpedo firing solution. The rule was: keep the scope up as little as possible. A careless periscope look was an invitation to a depth charge attack."},

{"chunk_id": "pam_041", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What is a conning tower?",
 "questions": ["What was the conning tower on a submarine?", "What happened in the conning tower?", "What is the conning tower fairwater?"],
 "text": "What is a conning tower?\n\nOn a WWII fleet submarine, the conning tower was a small cylindrical compartment \u2014 barely large enough for a handful of men \u2014 located between the bridge above and the control room below. It was the nerve center of an attack: the periscopes, the Torpedo Data Computer (TDC), the radar display, and the main helm were all located here.\n\nDuring a torpedo attack, the captain stood at the periscope in the conning tower while the TDC operator tracked the target and calculated the firing solution. The fire control party \u2014 captain, exec, TDC operator, and assistant \u2014 worked in very close quarters. It could get intense.\n\nThe word \u201cconning tower\u201d is also sometimes used loosely to refer to the entire raised structure above the main deck \u2014 the \u201csail\u201d or \u201cfairwater\u201d \u2014 which contains the bridge at the top. Strictly speaking, the conning tower is the pressure hull compartment inside that structure, while the outer shell is called the fairwater. On the Pampanito, you can visit the actual conning tower compartment and see the periscopes and equipment in place."},

{"chunk_id": "pam_042", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How did they control the depth of a submarine?",
 "questions": ["How did submarines maintain depth underwater?", "How did submarines go deeper or shallower?", "What are diving planes on a submarine?"],
 "text": "How did they control the depth of a submarine?\n\nA submerged submarine used two systems in combination to control its depth.\n\nThe first was buoyancy: by flooding or pumping out water from ballast and trim tanks, the submarine could be made slightly heavier or lighter than the water it displaced. When properly \u201ctrimmed,\u201d the boat was in neutral buoyancy at depth, neither rising nor sinking on its own.\n\nThe second system was the diving planes \u2014 pairs of horizontal fins, one set near the bow and one near the stern. Like the elevators on an airplane, the planes changed the angle of the hull and drove the boat up or down when it was moving forward. The planesmen \u2014 usually two sailors sitting side by side in the control room \u2014 operated these controls constantly, making small adjustments to hold the ordered depth. Holding a steady depth in rough water or changing thermoclines required constant attention.\n\nThe two systems worked together. Ballast and trim tanks gave coarse buoyancy control. The planes gave fine dynamic depth control while the boat was underway."},

{"chunk_id": "pam_043", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What were the biggest dangers for submarine crews?",
 "questions": ["What dangers did submariners face?", "How dangerous was it to serve on a submarine?", "What could kill a submarine crew?"],
 "text": "What were the biggest dangers for submarine crews?\n\nThe submarine service was the most dangerous assignment in the US Navy during World War II. Roughly one in five US submariners who went on patrol did not return \u2014 a casualty rate exceeded by no other branch of the American armed forces.\n\nThe primary threat was enemy anti-submarine warfare: destroyer escorts equipped with sonar and depth charges. A depth charge had to explode within about 50 feet to be lethal, but a sustained pattern from multiple destroyers could keep a submarine deep for hours, exhausting batteries and crew alike, until a critical failure forced it up. Enemy aircraft \u2014 especially later in the war \u2014 caught submarines on the surface and bombed or strafed them.\n\nMines were another major threat, especially in shallow coastal waters. Other boats were lost to operational accidents: a circular run by a malfunctioning torpedo, a diving casualty in training, or a collision. And there was always the possibility of a patrol going simply \u201cmissing\u201d with no known cause \u2014 about eight boats fall in that category. Whatever the cause, if you weren\u2019t coming home, no one would know until you were long overdue."},

{"chunk_id": "pam_044", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What caused the most submarine losses in WWII?",
 "questions": ["Why did American submarines get sunk?", "How were American submarines lost in the war?", "What sank US submarines in WWII?"],
 "text": "What caused the most submarine losses in WWII?\n\nOf the 52 US submarines lost in World War II, the single largest cause was enemy anti-submarine warfare \u2014 depth charges and bombs from Japanese surface ships and aircraft. Destroyers and destroyer escorts were the submarine\u2019s natural enemy, armed with sonar to track submerged boats and depth charges to attack them.\n\nMines accounted for a smaller but significant number of losses, particularly in the early part of the war when charting of enemy minefields was incomplete. Some boats were lost entering or exiting enemy harbors and coastal waters.\n\nA handful of submarines were lost to operational accidents \u2014 training accidents, diving casualties, or mechanical failures. A few were lost to friendly fire. And for about eight US submarines that disappeared during the war, the cause was never determined, and they remain \u201clost to causes unknown.\u201d Their crews are carried on the Navy\u2019s rolls as \u201con eternal patrol.\u201d\n\nJapanese anti-submarine tactics improved significantly as the war progressed. In 1942 and early 1943, very few US submarines were lost. By 1944 and 1945, as Japan\u2019s ASW forces became better equipped and submarines operated increasingly in shallow, confined waters, the loss rate climbed."},

{"chunk_id": "pam_045", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "Were American torpedo problems fixed during the war?",
 "questions": ["Why did US torpedoes fail?", "What was wrong with American torpedoes?", "Were US torpedo problems repaired during WWII?"],
 "text": "Were American torpedo problems fixed during the war?\n\nYes, but it took nearly two years of war and enormous frustration to sort out. The standard US submarine torpedo in 1941 \u2014 the Mark 14 \u2014 had at least three serious defects, each of which took time to identify and correct.\n\nThe first problem was depth-keeping: the Mark 14 ran about 10 feet deeper than set, meaning torpedoes aimed at a ship\u2019s waterline passed harmlessly under the keel. This was confirmed by testing in 1942 and corrected.\n\nThe second problem was the Mark 6 magnetic exploder \u2014 designed to detonate under a ship\u2019s hull using its magnetic field. It was far too sensitive and detonated prematurely or not at all. Submarines began deactivating it independently in 1943, and the Navy officially ordered it deactivated in October 1943.\n\nThe third problem was the contact exploder\u2019s firing pins: when a torpedo struck at a 90-degree angle (a direct hit), the impact was so forceful that the firing pin mechanism crushed instead of firing. This was identified and fixed in mid-1943 with stronger pins and modified angles.\n\nBy late 1943 and into 1944, all three fixes were in place. US torpedo reliability improved dramatically, and the submarine force\u2019s effectiveness surged accordingly."},

{"chunk_id": "pam_046", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "Who was the captain of the Pampanito?",
 "questions": ["Who commanded the Pampanito?", "Who was in charge of the Pampanito during WWII?", "What was the commanding officer of the Pampanito?"],
 "text": "Who was the captain of the Pampanito?\n\nThe Pampanito served under two commanding officers during her six war patrols in World War II.\n\nLieutenant Commander Charles B. Jackson Jr. commanded Pampanito on her first two patrols, beginning when the boat commissioned in November 1943. Under Jackson, Pampanito conducted patrols in the Western Pacific and established herself as an effective boat.\n\nLieutenant Commander Paul E. Summers took command before the third patrol and led Pampanito through patrols three, four, five, and six. Summers commanded the boat during its most famous action: the September 1944 patrol in which Pampanito, operating with a wolf pack, helped attack a Japanese convoy \u2014 and then discovered that the convoy was carrying British and Australian prisoners of war. Pampanito rescued 73 men from the water in one of the most dramatic humanitarian missions in submarine history. Summers was awarded the Navy Cross for this patrol.\n\nBoth commanders were decorated for their service. The Pampanito was awarded six battle stars for her WWII service."},

{"chunk_id": "pam_047", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What is the silent service?",
 "questions": ["Why is the submarine force called the silent service?", "Where does the name silent service come from?", "What does silent service mean?"],
 "text": "What is the silent service?\n\n\u201cThe Silent Service\u201d is the traditional nickname for the United States submarine force. The name has two meanings, both rooted in how submarines operated in World War II.\n\nThe first meaning is tactical. Submarines depended on silence and stealth. They operated alone, deep, and invisible. Every sound the crew made could be heard by enemy sonar. When submerged and evading, crew members spoke in whispers, removed their shoes, and tiptoed through the boat. The machinery was quieted as much as possible. The submarine\u2019s survival depended on being quieter than the water around it.\n\nThe second meaning is institutional. Submarine operations were classified. Crews returning from patrol could not tell their families where they had been, what they had done, or what ships they had sunk. A submariner could not explain why he couldn\u2019t talk about his service; he could only say he couldn\u2019t. The men came home, said nothing, and went out again. For years after the war, much of the submarine record remained classified.\n\nTogether, those two meanings \u2014 tactical stealth and institutional secrecy \u2014 gave the submarine force its enduring name."},

{"chunk_id": "pam_048", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How old were the men who served on submarines?",
 "questions": ["How young were submariners in WWII?", "What was the average age of a submarine crew?", "How old were enlisted sailors on a submarine?"],
 "text": "How old were the men who served on submarines?\n\nSubmarine crews during World War II were young by any measure. Enlisted men were typically 17 to 24 years old, with many in their late teens or early twenties. Officers were somewhat older \u2014 ensigns fresh from submarine school might be 22 or 23, while a commanding officer was usually in his late twenties or early thirties. By the standards of other military commands, submarine captains were very young men.\n\nAll submarine service was voluntary. The Navy screened heavily for physical fitness, mental aptitude, and temperament. Men had to pass a demanding physical examination \u2014 good eyesight, hearing, and psychological screening for tolerance of confined spaces. Then they had to complete submarine school and actually earn their qualifications at sea.\n\nThe youth of the crews is perhaps surprising given the demands placed on them. These were teenagers and young men in their early twenties operating some of the most complex fighting machinery of the era, in life-or-death situations, far from home on patrols lasting two months. Veterans who survived the war often speak of being astonished, in retrospect, at how young they were \u2014 and how little they worried about it at the time."},

{"chunk_id": "pam_049", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "Were there African American sailors on WWII submarines?",
 "questions": ["Did Black sailors serve on submarines?", "Were submarines segregated in WWII?", "Were there minority sailors on WWII submarines?"],
 "text": "Were there African American sailors on WWII submarines?\n\nDuring World War II, the US Navy was racially segregated. African American sailors were largely confined to the messman and steward branches \u2014 the cooks and personal servants for officers \u2014 across all seagoing branches, including submarines. Very few Black sailors served in technical or combat roles in the submarine force during the war.\n\nThe submarine service reflected the Navy\u2019s broader segregation policy, established by regulations and reinforced by long-standing tradition. Even those African American sailors who did serve aboard submarines in steward roles often faced discrimination in shore facilities and port towns.\n\nPresident Truman\u2019s Executive Order 9981 in 1948 mandated integration of all armed forces, and the Navy moved toward full integration in the early 1950s. Today the submarine force is fully integrated throughout its ranks, and women have served on submarines since 2010."},

{"chunk_id": "pam_050", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How did submarines get fuel and supplies during a patrol?",
 "questions": ["How did submarines refuel during a war patrol?", "Where did submarines get supplies at sea?", "How were submarines resupplied?"],
 "text": "How did submarines get fuel and supplies during a patrol?\n\nUS fleet submarines were largely self-sufficient for the duration of a war patrol \u2014 typically 45 to 75 days. They departed with full fuel tanks, a full torpedo load, and enough food to feed 80 men for the patrol. Replenishment at sea was possible but not routine.\n\nThe primary supply bases were Pearl Harbor, Hawaii, and \u2014 as the war advanced westward \u2014 Midway Atoll, Majuro, Guam, and other forward bases. Submarine tenders \u2014 large ships like USS Fulton or USS Proteus \u2014 were moored at these bases and served as floating machine shops, supply depots, and rest facilities for crews between patrols. When a submarine returned from patrol, the tender took care of everything: fuel, torpedoes, food, spare parts, and repair of any damage.\n\nAt-sea transfers from tenders or other submarines were technically possible and occasionally done for special missions but were logistically complex and risky. For a normal war patrol, the submarine carried everything it needed and relied on nothing until it returned to port."},

{"chunk_id": "pam_051", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What does it smell like inside a submarine?",
 "questions": ["How did submarines smell?", "What was the odor like on a submarine?", "Did submarines have a distinctive smell?"],
 "text": "What does it smell like inside a submarine?\n\nVeterans who served on WWII submarines are remarkably consistent in their answer: diesel fuel and unwashed men, with various undertones depending on where in the boat you were.\n\nThe dominant smell was diesel. The engines were inside the boat, the fuel was in tanks throughout the hull, and every surface absorbed the smell of petroleum over time. Clothes, blankets, food \u2014 everything took on a diesel-and-oil character after a few days at sea. The engine rooms were the worst, but the smell permeated the entire boat.\n\nAdd to that: 80 men in a sealed metal tube for two months with almost no fresh water for bathing, no laundry, and cooking happening around the clock. When the submarine was charging batteries, hydrogen gas from the battery cells added a sharp chemical note. The galley contributed cooking smells. In the after battery room, where many of the crew bunked, a faint battery acid smell was always present.\n\nLong-time veterans say they stopped noticing it after a day or two. The sailors on the dock welcoming a returning submarine noticed it very clearly from a distance."},

{"chunk_id": "pam_052", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How did submarine crews get mail from home?",
 "questions": ["Did submariners get letters from home?", "Could submarine crews receive mail on patrol?", "How did families send mail to submarines?"],
 "text": "How did submarine crews get mail from home?\n\nWhile a submarine was at sea on patrol, there was no mail delivery. The boat was completely radio-silent except for receiving encoded operational messages, and those messages carried no personal correspondence. For 60 or 70 days at sea, a submariner had no news from home whatsoever.\n\nMail sent to submarines was held at the submarine base \u2014 usually addressed to the boat\u2019s name in care of Fleet Post Office. When the submarine returned from patrol and tied up to the submarine tender, weeks of accumulated letters and packages were waiting.\n\nThe volume of letters a man received on return from patrol was often very large, and it was common to spend the first day or two just reading. For crewmen with wives, children, or parents back home, those letters were a lifeline to the world they had left behind.\n\nFamilies were told to write frequently because letters would arrive in batches \u2014 but they had no reliable way to know when their sailor was due back, or whether he was still alive. The uncertainty was one of the hardest parts for families."},

{"chunk_id": "pam_053", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What happened when a submarine returned to port?",
 "questions": ["How were submarine crews welcomed back from patrol?", "What was return from patrol like for submariners?", "What did submariners do after a war patrol?"],
 "text": "What happened when a submarine returned to port?\n\nReturning from a war patrol was one of the defining experiences of submarine service. After 60 or more days at sea, the boat tied up to its submarine tender, and the transition from patrol to port began immediately.\n\nThe first pleasures were simple and powerful: fresh milk, fresh fruit, fresh baked bread \u2014 food that had no place on a patrol, where everything was canned or frozen. A hot shower. A real bed that didn\u2019t move. A beer ration issued by the Navy. The submarine tender\u2019s crew took over the boat for repairs and provisioning, and the submarine\u2019s crew was free to rest.\n\nA formal debriefing followed, where the officers reported the patrol\u2019s results and any intelligence observations. Then came a rest period \u2014 typically two weeks at a rest camp at a location like the Royal Hawaiian Hotel in Honolulu, or a camp on Guam or Midway. Swimming, food, drinks, and sleep.\n\nAfter rest, the crew returned to the tender to supervise the reloading of torpedoes, provisioning, and repairs before the next patrol began. The cycle \u2014 patrol, rest, prepare, patrol again \u2014 continued until the war ended or the boat was lost."},

{"chunk_id": "pam_054", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What is a wolf pack?",
 "questions": ["How did wolf pack tactics work?", "Did US submarines hunt in packs?", "Did American submarines use wolf pack tactics?"],
 "text": "What is a wolf pack?\n\nA wolf pack is a coordinated group of submarines assigned to attack the same convoy or patrol area together. The tactic was pioneered by Germany\u2019s Admiral Karl D\u00f6nitz, who used large packs of U-boats in the Atlantic to overwhelm convoy defenses that could only track one submarine at a time.\n\nThe US Navy developed its own version, called \u201ccoordinated attack groups,\u201d typically two to four submarines working together. Unlike the German wolf packs, which were directed by a shore headquarters, American groups operated with more independence, coordinating by radio once contact was made. The idea was the same: while the escorts chased one submarine, the others could attack from different directions.\n\nThe Pampanito participated in a coordinated attack group on its famous third war patrol in September 1944, operating with USS Growler (SS-215) and USS Sealion II (SS-315). They attacked a Japanese convoy \u2014 and that attack led directly to the discovery of hundreds of British and Australian prisoners of war in the water, setting off the dramatic rescue for which the Pampanito is best known.\n\nAmerican wolf packs contributed significantly to the destruction of Japan\u2019s merchant fleet, cutting off the supply lines that kept Japan\u2019s island garrisons and war economy alive."},

{"chunk_id": "pam_055", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "Did the Pampanito rescue people from the ocean?",
 "questions": ["What was the Pampanito rescue mission?", "Did the Pampanito save POWs?", "What was the prisoner rescue in 1944?", "Did the Pampanito save Australian and British prisoners?"],
 "text": "Did the Pampanito rescue people from the ocean?\n\nYes \u2014 it is one of the most dramatic rescue operations in submarine history. On its third war patrol in September 1944, the Pampanito was part of a wolf pack that attacked Japanese convoy HI-72 in the South China Sea. What the submarines did not know at the time was that two ships in the convoy \u2014 the Rakuyo Maru and Kachidoki Maru \u2014 were carrying over 2,200 British and Australian prisoners of war being transported to labor camps.\n\nAfter the attack, Pampanito surfaced and began finding survivors in the water \u2014 gaunt, oil-covered men who turned out to be Allied POWs. Commander Paul Summers began pulling men aboard immediately. Over the course of about nine hours, Pampanito rescued 73 British and Australian survivors. USS Sealion II rescued an additional 54. Other submarines and surface ships reached the area and rescued more.\n\nOf the 2,200 POWs who had been aboard those ships, approximately 159 were rescued. The rest perished \u2014 many drowned; others died in the days after rescue from the effects of years of brutal captivity. Pampanito carried her 73 survivors back to port, with the injured crowding every available space on the boat. The rescue is memorialized in the exhibits aboard the Pampanito today."},

{"chunk_id": "pam_056", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What happened to men who were killed on a submarine patrol?",
 "questions": ["What happened when a submariner was killed at sea?", "How were submarine casualties handled during a patrol?", "Were submariners buried at sea?"],
 "text": "What happened to men who were killed on a submarine patrol?\n\nIf a sailor died while the submarine was at sea on patrol \u2014 from combat injury, accident, or illness \u2014 he was buried at sea. There was no option to preserve the body or return it to port: submarines had no morgue, and a 60-day patrol left no practical alternative. The captain would conduct a brief ceremony, and the man would be committed to the ocean.\n\nFor families at home, the process was agonizing in its uncertainty. The Navy did not broadcast results from individual submarines, and any message home would have compromised operational security. Families received only a telegram from the Navy when a man\u2019s status changed. If a submarine went missing and was overdue, the families of every man aboard received a \u201cmissing in action\u201d notification \u2014 but no explanation and no certainty.\n\nOf the 52 US submarines lost in World War II, most were lost with all hands, their crews still aboard somewhere in the Pacific. The submarine community calls them \u201con eternal patrol.\u201d In total, approximately 3,500 US submariners died in the war \u2014 the highest loss rate, per capita, of any branch of the American armed forces."},

{"chunk_id": "pam_057", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What happened to the Japanese submarine force in WWII?",
 "questions": ["How effective were Japanese submarines?", "Did Japan have submarines in WWII?", "What did Japanese submarines do in WWII?"],
 "text": "What happened to the Japanese submarine force in WWII?\n\nJapan entered World War II with one of the largest submarine fleets in the world \u2014 over 60 ocean-going submarines, with more under construction. In some respects Japanese submarines were technically impressive, and Japanese torpedoes (the oxygen-powered Type 91 and Type 95) were among the best in the world.\n\nBut the Imperial Japanese Navy made a strategic choice that limited its submarines\u2019 impact: instead of using them primarily against Allied merchant shipping \u2014 the approach that strangled Japan\u2019s own supply lines \u2014 Japanese doctrine emphasized attacks on warships. They achieved notable successes (the heavy cruiser Indianapolis was sunk by submarine I-58 in July 1945, one of the worst naval disasters in US history), but Japanese submarines never seriously threatened Allied supply lines across the Pacific.\n\nAs the war progressed, Japanese submarines were increasingly diverted to supply missions \u2014 resupplying isolated island garrisons that could no longer be reached by surface ship. This consumed much of their offensive potential.\n\nBy the war\u2019s end, the vast majority of Japan\u2019s submarine fleet had been sunk by US destroyers and aircraft, aided by Allied signals intelligence that often revealed their positions."},

{"chunk_id": "pam_058", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How did US submarines compare to German U-boats?",
 "questions": ["Were US submarines better than German U-boats?", "What was the difference between US submarines and German U-boats?", "How were American submarines different from German ones?"],
 "text": "How did US submarines compare to German U-boats?\n\nAmerican fleet submarines and German U-boats were the two most effective submarine forces of World War II, but they were built for very different purposes and operated in completely different theaters.\n\nUS fleet submarines like the Pampanito were much larger: about 310 feet long with a displacement of over 1,500 tons submerged, compared to roughly 220 feet and 870 tons for the standard German Type VIIC U-boat. The greater size gave US submarines much longer range (over 11,000 miles on the surface), better habitability, and air conditioning that made long Pacific patrols bearable in tropical heat.\n\nGerman U-boats were purpose-built for the North Atlantic \u2014 shorter-range operations from European bases against dense convoy routes. They operated in large wolf packs of 10 to 20 submarines directed from shore headquarters, with tight coordination. Germany built nearly 1,000 U-boats during the war, compared to about 200 US fleet submarines.\n\nBoth forces were devastating in their own theaters. US submarines sank approximately 55% of all Japanese merchant tonnage, strangling Japan\u2019s ability to fuel and supply its forces. German U-boats sank over 3,000 Allied ships. Both paid heavily: Germany lost over 700 U-boats and roughly 30,000 men; the US lost 52 submarines and about 3,500 men."},

# Paraphrase aliases
{"chunk_id": "pam_059", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "How many men were on a submarine crew?",
 "text": "How many men were on a submarine crew?\n\nA US fleet submarine like the Pampanito carried about 80 men \u2014 roughly 10 officers and 70 enlisted sailors. The Balao class, to which Pampanito belongs, had a maximum complement of 85, though wartime patrols often ran slightly under that.\n\nIn a vessel 311 feet long and less than 28 feet at its widest, those 80 men lived, slept, worked, ate, and stood watch in conditions of extraordinary crowding. There were never enough bunks for everyone at the same time, which is why the \u201chot bunk\u201d system was used \u2014 a sailor coming off watch would climb into the bunk just vacated by someone going on watch, the mattress still warm.\n\nDespite the cramped conditions, a submarine crew functioned as a highly trained team. Every man had to qualify in every major system aboard \u2014 not just his own job. In an emergency, you might need any sailor to operate any piece of equipment. The Navy\u2019s word for this was \u201cqualified in submarines,\u201d and earning it was a point of pride."},

{"chunk_id": "pam_060", "doc_type": "pam_faq", "source": "pampanito_docent", "type": "faq",
 "title": "What is a crash dive?",
 "text": "What is a crash dive?\n\nA crash dive is an emergency dive \u2014 practiced constantly until the entire crew could execute it in their sleep. Typically triggered by a sighting of an enemy aircraft or surface ship, the goal was to get below the surface as fast as possible.\n\nThe diving alarm \u2014 two blasts of the klaxon, the distinctive \u201cah-OOH-ga\u201d sound \u2014 was the signal. Every man on the bridge scrambled below in a fixed order: lookouts first, then the officer of the deck, then the captain last, pulling the hatch shut behind him. The main ballast tank vents were opened and water flooded in. Full negative tanks were flooded for additional weight. The diving planes were angled steeply. The diesel engines were secured and the electric motors engaged.\n\nA well-drilled fleet submarine crew could go from surfaced to periscope depth \u2014 roughly 63 feet \u2014 in 30 to 60 seconds. Getting those extra few seconds could be the difference between escaping and being bombed. Submariners drilled on the crash dive over and over again until every motion was automatic."},

]

corpus_path = "corpora/dieselsubs_faq_corpus.jsonl"
with open(corpus_path, "a") as f:
    for entry in NEW_ENTRIES:
        f.write(json.dumps(entry) + "\n")

print(f"Appended {len(NEW_ENTRIES)} entries (pam_035 through pam_060)")
